### PR TITLE
Circe - object with empty properties - codegen fix

### PR DESCRIPTION
**Pull request by justcoon**
fixes in relation to #1138

### CODE REVIEW

**Review by kelnos — APPROVED** [review]
lgtm, thank you!

**Comment by kelnos** [comment]
hmm, looks like something got merged since you branched that has caused conflicts.  can you fix that up?

**Comment by justcoon** [comment]
@kelnos 
build failed on

`scala.reflect.internal.FatalError: Error accessing /home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lightbend/paradox/paradox_2.12/0.5.5/paradox_2.12-0.5.5.jar`

it is look like some temporary error, is it possible to run it again?

**Comment by justcoon** [comment]
oh, it failed with another error :(

```
Post job cleanup.
/usr/bin/tar -cz -f /home/runner/work/_temp/9f9c99c6-146e-484a-9620-fde886bfc9f2/cache.tgz -C /home/runner/.cache/coursier .
Warning: read ECONNRESET
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}
```

**Comment by kelnos** [comment]
Ugh, what... ok let's try for a third time 😬

**Comment by kelnos** [comment]
Ok, looks like that worked!  Thanks so much for taking this on, @justcoon!  Really appreciate it.

**Comment by justcoon** [comment]
I'm glad it worked out. Thanks for help.

**Pull request merged**
