### PR TITLE
[WIP] zio-http support

### PR DESCRIPTION
**Pull request by zeal18**
So far I've defined the module, but it won't compile because it appeared that the zio-http is not published yet (local build requires building other dependencies locally as well and couldn't be verified in the CI). The plan is the following:
* wait until zio-http finalises its api and publishes at least the first version (during this period I can start experimenting locally)
* implement routes/endpoints/http-app generation using existing circe models generator
* add zio-json or/and zio-schema models generation support

Issue:  #1038

### CODE REVIEW

**Comment by blast-hardcheese** [comment]
Understood about the dependency.

I've added the `minor` label to this PR which bypasses the infrastructure that favors stable-only module dependencies inside guardrail.

That should help the CI get further.

**Comment by zeal18** [comment]
Hi @blast-hardcheese!
I found some time to continue working on this feature, but I'm struggling with the framework structure: it's too coupled. I think it's time to revise it.

The problem: the framework is too coupled and forces plugins to follow its ways. It defines generators interfaces and implements a common logic using them. The common logic prevents plugins to evolve independently, forces to them some common dependencies (for example cats and circe libraries) and complicates generating more "natural" for a particular plugin code.

Suggested solution: get rid of the common logic. Of cause the OpenAPI parsing logic should stay shared, but plugins should become as independent as possible, ideally, they could become even a separate applications

WDYT?

**Comment by blast-hardcheese** [comment]
This is what I was attempting to do with the modules and SPI; I agree with the difficulties you're experiencing, the explosion of build tooling requirements is concerning though. I will try to respond with a more thorough consideration within the next week, I've been pulling a lot of long nights recently.

**Comment by blast-hardcheese** [comment]
@zeal18 How do you want to proceed here, and do you still have interest in tending to this PR? Otherwise I can take a pass on getting the branch rebased, time permitting. Your choice.

**Comment by zeal18** [comment]
> @zeal18 How do you want to proceed here, and do you still have interest in tending to this PR? Otherwise I can take a pass on getting the branch rebased, time permitting. Your choice.

Hi @blast-hardcheese! yes, I'm still considering continuing working on this, but I have a lack of time at the moment. I'll try to keep it moving starting from rebasing

**Comment by blast-hardcheese** [comment]
@zeal18 if there's anything I can do to help please let me know.

**Pull request closed without merging**
